services:
  asphyxia:
    # Use your Docker Hub username.
    # Example: kaanreal/asphyxia:latest
    image: kaanreal/asphyxia:latest
    container_name: asphyxia
    restart: unless-stopped
    ports:
      - "8083:8083"
    volumes:
      # PERSISTENCE:
      # Maps the host folder to the container's data directory.
      
      # usage: /path/to/local/folder:/data
      - /home/pi/asphyxia-data:/data
      
    environment:
      - TZ=Europe/Amsterdam
