version: "3"
services:
    asphyxia:
        image: kaanreal/asphyxia:latest
        # alternaive: ghcr.io/kaanreal/asphyxia:latest
        container_name: asphyxia
        restart: always
        ports:
            - "8083:8083"
            - "5700:5700"
        volumes:
            # Replace the path on the left with your local Pi directory
            - /home/pi/asphyxia-server:/app/data
